apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: client
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: docker-js-stack-client
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}